DROP SEQUENCE seq_country_pk;
CREATE SEQUENCE seq_country_pk START WITH 1 INCREMENT BY 1;
DROP SEQUENCE seq_stamp_list_pk;
CREATE SEQUENCE seq_stamp_list_pk START WITH 1 INCREMENT BY 1;
DROP SEQUENCE seq_stamp_catalog_pk;
CREATE SEQUENCE seq_stamp_catalog_pk START WITH 1 INCREMENT BY 1;