INSERT INTO country (country_code, country_name) VALUES ('AD','Aden');
INSERT INTO country (country_code, country_name) VALUES ('AF','Afghanistan');
INSERT INTO country (country_code, country_name) VALUES ('AJ','Ajman');
INSERT INTO country (country_code, country_name) VALUES ('AL','Albania');
INSERT INTO country (country_code, country_name) VALUES ('DZ','Algeria');
INSERT INTO country (country_code, country_name) VALUES ('AD-ES','Andorra, Spanish Administration');
INSERT INTO country (country_code, country_name) VALUES ('AO','Angola');
INSERT INTO country (country_code, country_name) VALUES ('AG','Antigua and Barbuda');
INSERT INTO country (country_code, country_name) VALUES ('AR','Argentina');
INSERT INTO country (country_code, country_name) VALUES ('AU','Australia');
INSERT INTO country (country_code, country_name) VALUES ('AQ','Australian Antarctic Territory (AAT)');
INSERT INTO country (country_code, country_name) VALUES ('AT','Austria');
INSERT INTO country (country_code, country_name) VALUES ('AZ','Azerbaijan');
INSERT INTO country (country_code, country_name) VALUES ('PT-AZ','Azores');
INSERT INTO country (country_code, country_name) VALUES ('BS','Bahamas');
INSERT INTO country (country_code, country_name) VALUES ('PK-BH','Bahawalpur');
INSERT INTO country (country_code, country_name) VALUES ('BH','Bahrain');
INSERT INTO country (country_code, country_name) VALUES ('BD','Bangladesh');
INSERT INTO country (country_code, country_name) VALUES ('BB','Barbados');
INSERT INTO country (country_code, country_name) VALUES ('BX','Barbuda');
INSERT INTO country (country_code, country_name) VALUES ('BY','Belarus');
INSERT INTO country (country_code, country_name) VALUES ('BE-CD','Belgian Congo');
INSERT INTO country (country_code, country_name) VALUES ('BE','Belgium');
INSERT INTO country (country_code, country_name) VALUES (':B','Belgium');
INSERT INTO country (country_code, country_name) VALUES ('BE','Belgium, German Occupation in WWI');
INSERT INTO country (country_code, country_name) VALUES ('BJ','Benin');
INSERT INTO country (country_code, country_name) VALUES ('BJ','Benin: Illegal Stamps');
INSERT INTO country (country_code, country_name) VALUES ('DE','Berlin');
INSERT INTO country (country_code, country_name) VALUES ('BM','Bermuda');
INSERT INTO country (country_code, country_name) VALUES ('BT','Bhutan');
INSERT INTO country (country_code, country_name) VALUES ('BO','Bolivia');
INSERT INTO country (country_code, country_name) VALUES ('BA','Bosnia and Herzegovina');
INSERT INTO country (country_code, country_name) VALUES ('BA','Bosnia and Herzegovina, Austro-Hungarian Admin.');
INSERT INTO country (country_code, country_name) VALUES ('AT-BA','Bosnia and Herzegovina, Austro-Hungarian Admin.');
INSERT INTO country (country_code, country_name) VALUES ('BW','Botswana');
INSERT INTO country (country_code, country_name) VALUES ('BR','Brazil');
INSERT INTO country (country_code, country_name) VALUES ('GB-GY','British Guiana');
INSERT INTO country (country_code, country_name) VALUES ('GB-BZ','British Honduras');
INSERT INTO country (country_code, country_name) VALUES ('VG','British Virgin Islands');
INSERT INTO country (country_code, country_name) VALUES ('BG','Bulgaria');
INSERT INTO country (country_code, country_name) VALUES ('MM','Burma');
INSERT INTO country (country_code, country_name) VALUES ('MM','Burma, Japanese Occupation');
INSERT INTO country (country_code, country_name) VALUES ('CV','Cabo Verde');
INSERT INTO country (country_code, country_name) VALUES ('KH','Cambodia');
INSERT INTO country (country_code, country_name) VALUES ('CM','Cameroon');
INSERT INTO country (country_code, country_name) VALUES ('CA','Canada');
INSERT INTO country (country_code, country_name) VALUES ('KY','Cayman Islands');
INSERT INTO country (country_code, country_name) VALUES ('CF','Central African Republic');
INSERT INTO country (country_code, country_name) VALUES ('PL-ML','Central Lithuania');
INSERT INTO country (country_code, country_name) VALUES ('LK','Ceylon');
INSERT INTO country (country_code, country_name) VALUES ('TD','Chad');
INSERT INTO country (country_code, country_name) VALUES ('CL','Chile');
INSERT INTO country (country_code, country_name) VALUES ('CN-IM','China');
INSERT INTO country (country_code, country_name) VALUES ('CN','China, People''s Republic');
INSERT INTO country (country_code, country_name) VALUES ('CN','China, Peoples Republic - East Lib. Area');
INSERT INTO country (country_code, country_name) VALUES ('CN-E ','China, Peoples Republic - East Lib. Area');
INSERT INTO country (country_code, country_name) VALUES ('CN','China, Peoples Republic - Northeast Lib. Area');
INSERT INTO country (country_code, country_name) VALUES ('CX','Christmas Island');
INSERT INTO country (country_code, country_name) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO country (country_code, country_name) VALUES ('CO','Colombia');
INSERT INTO country (country_code, country_name) VALUES ('CD','Congo, Democratic Republic (Kinshasa)');
INSERT INTO country (country_code, country_name) VALUES ('CG','Congo, Republic (Brazzaville)');
INSERT INTO country (country_code, country_name) VALUES ('CK','Cook Islands');
INSERT INTO country (country_code, country_name) VALUES ('CR','Costa Rica');
INSERT INTO country (country_code, country_name) VALUES ('AT-CT','Crete - Austrian Post Office');
INSERT INTO country (country_code, country_name) VALUES ('HR','Croatia');
INSERT INTO country (country_code, country_name) VALUES ('CR-ND','Croatia: Cinderella Stamps');
INSERT INTO country (country_code, country_name) VALUES ('CU','Cuba');
INSERT INTO country (country_code, country_name) VALUES ('CY','Cyprus');
INSERT INTO country (country_code, country_name) VALUES ('CZ','Czech Republic');
INSERT INTO country (country_code, country_name) VALUES ('CS','Czechoslovakia');
INSERT INTO country (country_code, country_name) VALUES ('DY','Dahomey');
INSERT INTO country (country_code, country_name) VALUES ('DM','Dominica');
INSERT INTO country (country_code, country_name) VALUES ('DO','Dominican Republic');
INSERT INTO country (country_code, country_name) VALUES ('DB','Dubai');
INSERT INTO country (country_code, country_name) VALUES ('PL-SO','Eastern Silesia');
INSERT INTO country (country_code, country_name) VALUES ('EC','Ecuador');
INSERT INTO country (country_code, country_name) VALUES ('EG','Egypt');
INSERT INTO country (country_code, country_name) VALUES ('SV','El Salvador');
INSERT INTO country (country_code, country_name) VALUES ('EE','Estonia');
INSERT INTO country (country_code, country_name) VALUES ('FK','Falkland Islands');
INSERT INTO country (country_code, country_name) VALUES ('FO','Faroe Islands');
INSERT INTO country (country_code, country_name) VALUES ('ES-FP','Fernando Poo');
INSERT INTO country (country_code, country_name) VALUES ('FJ','Fiji');
INSERT INTO country (country_code, country_name) VALUES ('FI','Finland');
INSERT INTO country (country_code, country_name) VALUES ('FR','France');
INSERT INTO country (country_code, country_name) VALUES ('FR-EQ','French Equatorial Africa');
INSERT INTO country (country_code, country_name) VALUES ('FR-OC','French Oceania');
INSERT INTO country (country_code, country_name) VALUES ('FR-SO','French Somaliland (Somali Coast)');
INSERT INTO country (country_code, country_name) VALUES ('FR-SU','French Sudan');
INSERT INTO country (country_code, country_name) VALUES ('FR-WA','French West Africa');
INSERT INTO country (country_code, country_name) VALUES ('GA','Gabon');
INSERT INTO country (country_code, country_name) VALUES ('GE','Georgia');
INSERT INTO country (country_code, country_name) VALUES ('DE','German Realm');
INSERT INTO country (country_code, country_name) VALUES ('DE','Germany, American-British Occ. (Bizone)');
INSERT INTO country (country_code, country_name) VALUES ('DD','Germany, Democratic Republic (DDR)');
INSERT INTO country (country_code, country_name) VALUES ('DE','Germany, Federal Republic');
INSERT INTO country (country_code, country_name) VALUES ('GH','Ghana');
INSERT INTO country (country_code, country_name) VALUES ('GI','Gibraltar');
INSERT INTO country (country_code, country_name) VALUES ('GB-GE','Gilbert and Ellice Islands');
INSERT INTO country (country_code, country_name) VALUES ('GB-GI','Gilbert Islands');
INSERT INTO country (country_code, country_name) VALUES ('GR','Greece');
INSERT INTO country (country_code, country_name) VALUES ('GD','Grenada');
INSERT INTO country (country_code, country_name) VALUES ('GD-GR','Grenada Grenadines');
INSERT INTO country (country_code, country_name) VALUES ('VC-GR','Grenadines of St. Vincent');
INSERT INTO country (country_code, country_name) VALUES ('VC-BQ','Grenadines of St. Vincent, Bequia');
INSERT INTO country (country_code, country_name) VALUES ('GP','Guadeloupe');
INSERT INTO country (country_code, country_name) VALUES ('GT','Guatemala');
INSERT INTO country (country_code, country_name) VALUES ('GG','Guernsey');
INSERT INTO country (country_code, country_name) VALUES ('GN','Guinea');
INSERT INTO country (country_code, country_name) VALUES ('GY','Guyana');
INSERT INTO country (country_code, country_name) VALUES ('AD-QSH','Hadhramaut, Qu''aiti (Shihr & Mukalla)');
INSERT INTO country (country_code, country_name) VALUES ('HT','Haiti');
INSERT INTO country (country_code, country_name) VALUES ('HT','Haiti: Cinderella Stamps');
INSERT INTO country (country_code, country_name) VALUES ('HN','Honduras');
INSERT INTO country (country_code, country_name) VALUES ('HU','Hungary');
INSERT INTO country (country_code, country_name) VALUES ('IS','Iceland');
INSERT INTO country (country_code, country_name) VALUES ('ES-IF','Ifni');
INSERT INTO country (country_code, country_name) VALUES ('IN','India');
INSERT INTO country (country_code, country_name) VALUES ('PT-IN','India, Portuguese');
INSERT INTO country (country_code, country_name) VALUES ('ID','Indonesia');
INSERT INTO country (country_code, country_name) VALUES ('ID-IB','Indonesia, West Irian');
INSERT INTO country (country_code, country_name) VALUES ('FR-IN','Inini');
INSERT INTO country (country_code, country_name) VALUES ('IR','Iran');
INSERT INTO country (country_code, country_name) VALUES ('IQ','Iraq');
INSERT INTO country (country_code, country_name) VALUES ('IE','Ireland');
INSERT INTO country (country_code, country_name) VALUES ('IM','Isle of Man');
INSERT INTO country (country_code, country_name) VALUES ('IL','Israel');
INSERT INTO country (country_code, country_name) VALUES ('IT','Italy');
INSERT INTO country (country_code, country_name) VALUES (':I','Italy');
INSERT INTO country (country_code, country_name) VALUES ('IT','Italy - Allied Occupation of Venezia-Giulia');
INSERT INTO country (country_code, country_name) VALUES ('AT','Italy - Occupation of Trentino and Venezia-Giulia');
INSERT INTO country (country_code, country_name) VALUES ('IT-RS','Italy, Social Republic');
INSERT INTO country (country_code, country_name) VALUES ('CI','Ivory Coast');
INSERT INTO country (country_code, country_name) VALUES ('JM','Jamaica');
INSERT INTO country (country_code, country_name) VALUES ('JP','Japan');
INSERT INTO country (country_code, country_name) VALUES ('JE','Jersey');
INSERT INTO country (country_code, country_name) VALUES ('MY-JO','Johore');
INSERT INTO country (country_code, country_name) VALUES ('JO','Jordan');
INSERT INTO country (country_code, country_name) VALUES ('KZ','Kazakhstan');
INSERT INTO country (country_code, country_name) VALUES ('MY-KE','Kedah');
INSERT INTO country (country_code, country_name) VALUES ('MY-KL','Kelantan');
INSERT INTO country (country_code, country_name) VALUES ('DR-KI','Kiao Chau');
INSERT INTO country (country_code, country_name) VALUES ('YU','Kingdom of Serbs, Croats and Slovenes');
INSERT INTO country (country_code, country_name) VALUES ('KW','Kuwait');
INSERT INTO country (country_code, country_name) VALUES ('LA','Laos');
INSERT INTO country (country_code, country_name) VALUES ('LA-PL','Laos');
INSERT INTO country (country_code, country_name) VALUES ('FR-LQ','Latakia');
INSERT INTO country (country_code, country_name) VALUES ('LV','Latvia');
INSERT INTO country (country_code, country_name) VALUES ('LB','Lebanon');
INSERT INTO country (country_code, country_name) VALUES ('LS','Lesotho');
INSERT INTO country (country_code, country_name) VALUES ('LR','Liberia');
INSERT INTO country (country_code, country_name) VALUES ('LY','Libya');
INSERT INTO country (country_code, country_name) VALUES ('LI','Liechtenstein');
INSERT INTO country (country_code, country_name) VALUES ('LT','Lithuania');
INSERT INTO country (country_code, country_name) VALUES ('LU','Luxembourg');
INSERT INTO country (country_code, country_name) VALUES ('MO','Macau');
INSERT INTO country (country_code, country_name) VALUES ('MG','Madagascar');
INSERT INTO country (country_code, country_name) VALUES ('SG-ST','Malaya, British Military Administration');
INSERT INTO country (country_code, country_name) VALUES ('MY','Malaysia');
INSERT INTO country (country_code, country_name) VALUES ('MV','Maldives');
INSERT INTO country (country_code, country_name) VALUES ('ML','Mali');
INSERT INTO country (country_code, country_name) VALUES ('MT','Malta');
INSERT INTO country (country_code, country_name) VALUES ('CN-MA','Manchukuo');
INSERT INTO country (country_code, country_name) VALUES ('MH','Marshall Islands, German Administration');
INSERT INTO country (country_code, country_name) VALUES ('FR-MA','Martinique');
INSERT INTO country (country_code, country_name) VALUES ('MR','Mauritania');
INSERT INTO country (country_code, country_name) VALUES ('MU','Mauritius');
INSERT INTO country (country_code, country_name) VALUES ('KL','Memel Territory');
INSERT INTO country (country_code, country_name) VALUES ('MX','Mexico');
INSERT INTO country (country_code, country_name) VALUES ('MC','Monaco');
INSERT INTO country (country_code, country_name) VALUES ('MN','Mongolia');
INSERT INTO country (country_code, country_name) VALUES ('ME','Montenegro');
INSERT INTO country (country_code, country_name) VALUES ('ME','Montenegro, Italian Occupation');
INSERT INTO country (country_code, country_name) VALUES ('MS','Montserrat');
INSERT INTO country (country_code, country_name) VALUES ('FR-MA','Morocco');
INSERT INTO country (country_code, country_name) VALUES ('MA','Morocco');
INSERT INTO country (country_code, country_name) VALUES ('GB-MA','Morocco, British Post Office');
INSERT INTO country (country_code, country_name) VALUES ('MZ','Mozambique');
INSERT INTO country (country_code, country_name) VALUES ('MZ-C ','Mozambique Company');
INSERT INTO country (country_code, country_name) VALUES ('NA','Namibia');
INSERT INTO country (country_code, country_name) VALUES ('NR','Nauru');
INSERT INTO country (country_code, country_name) VALUES ('NP','Nepal');
INSERT INTO country (country_code, country_name) VALUES ('NL','Netherlands');
INSERT INTO country (country_code, country_name) VALUES ('AN','Netherlands Antilles');
INSERT INTO country (country_code, country_name) VALUES ('NL-IN','Netherlands East Indies');
INSERT INTO country (country_code, country_name) VALUES ('NC','New Caledonia');
INSERT INTO country (country_code, country_name) VALUES ('NZ','New Zealand');
INSERT INTO country (country_code, country_name) VALUES ('NW','Newfoundland');
INSERT INTO country (country_code, country_name) VALUES ('NI','Nicaragua');
INSERT INTO country (country_code, country_name) VALUES ('NE','Niger');
INSERT INTO country (country_code, country_name) VALUES ('NB','North Borneo');
INSERT INTO country (country_code, country_name) VALUES ('GB-NR','Northern Rhodesia');
INSERT INTO country (country_code, country_name) VALUES ('NO','Norway');
INSERT INTO country (country_code, country_name) VALUES ('GB-NY','Nyasaland');
INSERT INTO country (country_code, country_name) VALUES ('OM','Oman');
INSERT INTO country (country_code, country_name) VALUES ('ZA-OR','Orange Free State');
INSERT INTO country (country_code, country_name) VALUES ('MY-PA','Pahang');
INSERT INTO country (country_code, country_name) VALUES ('PK','Pakistan');
INSERT INTO country (country_code, country_name) VALUES ('GB-PS','Palestine - British Mandate');
INSERT INTO country (country_code, country_name) VALUES ('PA','Panama');
INSERT INTO country (country_code, country_name) VALUES ('PG-PA','Papua');
INSERT INTO country (country_code, country_name) VALUES ('PG','Papua New Guinea');
INSERT INTO country (country_code, country_name) VALUES ('PY','Paraguay');
INSERT INTO country (country_code, country_name) VALUES ('MY-PE','Penang');
INSERT INTO country (country_code, country_name) VALUES ('MY-PK','Perak');
INSERT INTO country (country_code, country_name) VALUES ('MY-PS','Perlis');
INSERT INTO country (country_code, country_name) VALUES ('PE','Peru');
INSERT INTO country (country_code, country_name) VALUES ('PH','Philippines');
INSERT INTO country (country_code, country_name) VALUES ('PL','Poland');
INSERT INTO country (country_code, country_name) VALUES ('PT','Portugal');
INSERT INTO country (country_code, country_name) VALUES ('PT-GN','Portuguese Guinea');
INSERT INTO country (country_code, country_name) VALUES ('QA','Qatar');
INSERT INTO country (country_code, country_name) VALUES ('FR-RE','Reunion');
INSERT INTO country (country_code, country_name) VALUES ('RH','Rhodesia');
INSERT INTO country (country_code, country_name) VALUES ('GB-RH','Rhodesia and Nyasaland');
INSERT INTO country (country_code, country_name) VALUES ('RO','Romania');
INSERT INTO country (country_code, country_name) VALUES ('RW-U ','Ruanda-Urundi');
INSERT INTO country (country_code, country_name) VALUES ('RU','Russia');
INSERT INTO country (country_code, country_name) VALUES ('RU-FE','Russia, Civil War Regional Issues');
INSERT INTO country (country_code, country_name) VALUES ('RW','Rwanda');
INSERT INTO country (country_code, country_name) VALUES ('JP-RK','Ryukyu Islands');
INSERT INTO country (country_code, country_name) VALUES ('MY-SA','Sabah');
INSERT INTO country (country_code, country_name) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO country (country_code, country_name) VALUES ('LC','Saint Lucia');
INSERT INTO country (country_code, country_name) VALUES ('PM','Saint Pierre and Miquelon');
INSERT INTO country (country_code, country_name) VALUES ('VC','Saint Vincent and The Grenadines');
INSERT INTO country (country_code, country_name) VALUES ('WS','Samoa, German Administration');
INSERT INTO country (country_code, country_name) VALUES ('SM','San Marino');
INSERT INTO country (country_code, country_name) VALUES ('ST','São Tomé and Príncipe');
INSERT INTO country (country_code, country_name) VALUES ('MY-SR','Sarawak');
INSERT INTO country (country_code, country_name) VALUES ('SA','Saudi Arabia');
INSERT INTO country (country_code, country_name) VALUES ('MY-SE','Selangor');
INSERT INTO country (country_code, country_name) VALUES ('RS','Serbia');
INSERT INTO country (country_code, country_name) VALUES ('SC','Seychelles');
INSERT INTO country (country_code, country_name) VALUES ('AE-SH','Sharjah');
INSERT INTO country (country_code, country_name) VALUES ('SG','Singapore');
INSERT INTO country (country_code, country_name) VALUES ('SK','Slovakia');
INSERT INTO country (country_code, country_name) VALUES ('SI','Slovenia');
INSERT INTO country (country_code, country_name) VALUES ('YU','Slovenia - Kingdom of Serbs, Croats & Slovenes');
INSERT INTO country (country_code, country_name) VALUES ('SB','Solomon Islands');
INSERT INTO country (country_code, country_name) VALUES ('ZA','South Africa');
INSERT INTO country (country_code, country_name) VALUES ('GB-SR','Southern Rhodesia');
INSERT INTO country (country_code, country_name) VALUES ('NA-SW','South-West Africa');
INSERT INTO country (country_code, country_name) VALUES ('SU','Soviet Union, USSR');
INSERT INTO country (country_code, country_name) VALUES ('ES','Spain');
INSERT INTO country (country_code, country_name) VALUES ('ES','Spain: Barcelona Municipality');
INSERT INTO country (country_code, country_name) VALUES ('ES-AB','Spain: Cinderella Stamps');
INSERT INTO country (country_code, country_name) VALUES ('ES-GN','Spanish Guinea');
INSERT INTO country (country_code, country_name) VALUES ('ES-MA','Spanish Morocco');
INSERT INTO country (country_code, country_name) VALUES ('ES-MA','Spanish Morocco: Cinderella Stamps');
INSERT INTO country (country_code, country_name) VALUES ('ES-SH','Spanish Sahara');
INSERT INTO country (country_code, country_name) VALUES ('ES-AO','Spanish West Africa');
INSERT INTO country (country_code, country_name) VALUES ('LK','Sri Lanka');
INSERT INTO country (country_code, country_name) VALUES ('SG-ST','Straits Settlements');
INSERT INTO country (country_code, country_name) VALUES ('SD','Sudan');
INSERT INTO country (country_code, country_name) VALUES ('SE','Sweden');
INSERT INTO country (country_code, country_name) VALUES ('CH','Switzerland');
INSERT INTO country (country_code, country_name) VALUES ('SY','Syria');
INSERT INTO country (country_code, country_name) VALUES ('SY-UA','Syria');
INSERT INTO country (country_code, country_name) VALUES ('TW','Taiwan (Republic of China)');
INSERT INTO country (country_code, country_name) VALUES ('TX','Tannu Tuva');
INSERT INTO country (country_code, country_name) VALUES ('TZ','Tanzania');
INSERT INTO country (country_code, country_name) VALUES ('TH','Thailand');
INSERT INTO country (country_code, country_name) VALUES ('TL','Timor');
INSERT INTO country (country_code, country_name) VALUES ('TG','Togo');
INSERT INTO country (country_code, country_name) VALUES ('TG','Togo, German Administration');
INSERT INTO country (country_code, country_name) VALUES ('TN','Tunisia');
INSERT INTO country (country_code, country_name) VALUES ('AT-LE','Turkey - Austrian Post Offices');
INSERT INTO country (country_code, country_name) VALUES ('TR','Turkey: Cinderella Stamps');
INSERT INTO country (country_code, country_name) VALUES ('TR','Türkiye (Turkey)');
INSERT INTO country (country_code, country_name) VALUES ('TM','Turkmenistan');
INSERT INTO country (country_code, country_name) VALUES ('TC','Turks and Caicos Islands');
INSERT INTO country (country_code, country_name) VALUES ('UG','Uganda');
INSERT INTO country (country_code, country_name) VALUES ('UA','Ukraine');
INSERT INTO country (country_code, country_name) VALUES ('RU','Ukraine, German Occupation In WWII');
INSERT INTO country (country_code, country_name) VALUES ('GB','United Kingdom of Great Britain & Northern Ireland');
INSERT INTO country (country_code, country_name) VALUES ('GB-LU','United Kingdom: Private Post Offices');
INSERT INTO country (country_code, country_name) VALUES ('US','United States of America');
INSERT INTO country (country_code, country_name) VALUES ('NT-NY','UNO New York');
INSERT INTO country (country_code, country_name) VALUES ('BF','Upper Volta');
INSERT INTO country (country_code, country_name) VALUES ('UY','Uruguay');
INSERT INTO country (country_code, country_name) VALUES ('VA','Vatican City');
INSERT INTO country (country_code, country_name) VALUES ('VE','Venezuela');
INSERT INTO country (country_code, country_name) VALUES ('VN','Vietnam');
INSERT INTO country (country_code, country_name) VALUES ('VN-S ','Vietnam, South');
INSERT INTO country (country_code, country_name) VALUES ('WF','Wallis and Futuna');
INSERT INTO country (country_code, country_name) VALUES ('YE-AR','Yemen, Arab Republic');
INSERT INTO country (country_code, country_name) VALUES ('YE-K ','Yemen, Kingdom');
INSERT INTO country (country_code, country_name) VALUES ('YU','Yugoslavia');
INSERT INTO country (country_code, country_name) VALUES ('CD','Zaire');
INSERT INTO country (country_code, country_name) VALUES ('ZM','Zambia');
INSERT INTO country (country_code, country_name) VALUES ('TZ-ZB','Zanzibar');
COMMIT;